server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookingClient
            client-secret: G9NoDnf62v4YQeQmsU7TMZOqtZf3Pcm9
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${IDENTITY_ISSUER:http://localhost:8080/realms/bookingApp}
            
            
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}