server:
  port: ${SERVER_PORT:9094}

spring:
  application:
    name: SHOWSERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/showdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true    