spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: show-service
          uri: lb://SHOWSERVICE
          predicates:
            - Path=/shows/**
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookingApp
          jwk-set-uri: http://localhost:8080/realms/bookingApp/protocol/openid-connect/certs
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090      
